/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthAgendaRouteImport } from './routes/_auth/agenda'
import { Route as AuthAniversariantesRouteImport } from './routes/_auth/aniversariantes'
import { Route as AuthArquivosRouteImport } from './routes/_auth/arquivos'
import { Route as AuthConfiguracoesRouteImport } from './routes/_auth/configuracoes'
import { Route as AuthFotosRouteImport } from './routes/_auth/fotos'
import { Route as AuthGraficosRouteImport } from './routes/_auth/graficos'
import { Route as AuthGruposRouteImport } from './routes/_auth/grupos'
import { Route as AuthLicoesRouteImport } from './routes/_auth/licoes'
import { Route as AuthMembrosRouteImport } from './routes/_auth/membros'
import { Route as AuthMidiasRouteImport } from './routes/_auth/midias'
import { Route as AuthNotificacoesRouteImport } from './routes/_auth/notificacoes'
import { Route as AuthOfertaRouteImport } from './routes/_auth/oferta'
import { Route as AuthPerfilRouteImport } from './routes/_auth/perfil'
import { Route as AuthRelatoriosRouteImport } from './routes/_auth/relatorios'
import { Route as AuthUsuariosRouteImport } from './routes/_auth/usuarios'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgendaRoute = AuthAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAniversariantesRoute = AuthAniversariantesRouteImport.update({
  id: '/aniversariantes',
  path: '/aniversariantes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArquivosRoute = AuthArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfiguracoesRoute = AuthConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFotosRoute = AuthFotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGraficosRoute = AuthGraficosRouteImport.update({
  id: '/graficos',
  path: '/graficos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGruposRoute = AuthGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLicoesRoute = AuthLicoesRouteImport.update({
  id: '/licoes',
  path: '/licoes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMembrosRoute = AuthMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMidiasRoute = AuthMidiasRouteImport.update({
  id: '/midias',
  path: '/midias',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificacoesRoute = AuthNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOfertaRoute = AuthOfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerfilRoute = AuthPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRelatoriosRoute = AuthRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsuariosRoute = AuthUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/agenda': typeof AuthAgendaRoute
  '/aniversariantes': typeof AuthAniversariantesRoute
  '/arquivos': typeof AuthArquivosRoute
  '/configuracoes': typeof AuthConfiguracoesRoute
  '/fotos': typeof AuthFotosRoute
  '/graficos': typeof AuthGraficosRoute
  '/grupos': typeof AuthGruposRoute
  '/licoes': typeof AuthLicoesRoute
  '/membros': typeof AuthMembrosRoute
  '/midias': typeof AuthMidiasRoute
  '/notificacoes': typeof AuthNotificacoesRoute
  '/oferta': typeof AuthOfertaRoute
  '/perfil': typeof AuthPerfilRoute
  '/relatorios': typeof AuthRelatoriosRoute
  '/usuarios': typeof AuthUsuariosRoute
}
export interface FileRoutesByTo {
  '/bem-vindo': typeof BemVindoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/agenda': typeof AuthAgendaRoute
  '/aniversariantes': typeof AuthAniversariantesRoute
  '/arquivos': typeof AuthArquivosRoute
  '/configuracoes': typeof AuthConfiguracoesRoute
  '/fotos': typeof AuthFotosRoute
  '/graficos': typeof AuthGraficosRoute
  '/grupos': typeof AuthGruposRoute
  '/licoes': typeof AuthLicoesRoute
  '/membros': typeof AuthMembrosRoute
  '/midias': typeof AuthMidiasRoute
  '/notificacoes': typeof AuthNotificacoesRoute
  '/oferta': typeof AuthOfertaRoute
  '/perfil': typeof AuthPerfilRoute
  '/relatorios': typeof AuthRelatoriosRoute
  '/usuarios': typeof AuthUsuariosRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/bem-vindo': typeof BemVindoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_auth/agenda': typeof AuthAgendaRoute
  '/_auth/aniversariantes': typeof AuthAniversariantesRoute
  '/_auth/arquivos': typeof AuthArquivosRoute
  '/_auth/configuracoes': typeof AuthConfiguracoesRoute
  '/_auth/fotos': typeof AuthFotosRoute
  '/_auth/graficos': typeof AuthGraficosRoute
  '/_auth/grupos': typeof AuthGruposRoute
  '/_auth/licoes': typeof AuthLicoesRoute
  '/_auth/membros': typeof AuthMembrosRoute
  '/_auth/midias': typeof AuthMidiasRoute
  '/_auth/notificacoes': typeof AuthNotificacoesRoute
  '/_auth/oferta': typeof AuthOfertaRoute
  '/_auth/perfil': typeof AuthPerfilRoute
  '/_auth/relatorios': typeof AuthRelatoriosRoute
  '/_auth/usuarios': typeof AuthUsuariosRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bem-vindo'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/agenda'
    | '/aniversariantes'
    | '/arquivos'
    | '/configuracoes'
    | '/fotos'
    | '/graficos'
    | '/grupos'
    | '/licoes'
    | '/membros'
    | '/midias'
    | '/notificacoes'
    | '/oferta'
    | '/perfil'
    | '/relatorios'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bem-vindo'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/agenda'
    | '/aniversariantes'
    | '/arquivos'
    | '/configuracoes'
    | '/fotos'
    | '/graficos'
    | '/grupos'
    | '/licoes'
    | '/membros'
    | '/midias'
    | '/notificacoes'
    | '/oferta'
    | '/perfil'
    | '/relatorios'
    | '/usuarios'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/bem-vindo'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_auth/agenda'
    | '/_auth/aniversariantes'
    | '/_auth/arquivos'
    | '/_auth/configuracoes'
    | '/_auth/fotos'
    | '/_auth/graficos'
    | '/_auth/grupos'
    | '/_auth/licoes'
    | '/_auth/membros'
    | '/_auth/midias'
    | '/_auth/notificacoes'
    | '/_auth/oferta'
    | '/_auth/perfil'
    | '/_auth/relatorios'
    | '/_auth/usuarios'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  BemVindoRoute: typeof BemVindoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agenda': {
      id: '/_auth/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthAgendaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/aniversariantes': {
      id: '/_auth/aniversariantes'
      path: '/aniversariantes'
      fullPath: '/aniversariantes'
      preLoaderRoute: typeof AuthAniversariantesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/arquivos': {
      id: '/_auth/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthArquivosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/configuracoes': {
      id: '/_auth/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthConfiguracoesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fotos': {
      id: '/_auth/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof AuthFotosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/graficos': {
      id: '/_auth/graficos'
      path: '/graficos'
      fullPath: '/graficos'
      preLoaderRoute: typeof AuthGraficosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/grupos': {
      id: '/_auth/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthGruposRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/licoes': {
      id: '/_auth/licoes'
      path: '/licoes'
      fullPath: '/licoes'
      preLoaderRoute: typeof AuthLicoesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/membros': {
      id: '/_auth/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AuthMembrosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/midias': {
      id: '/_auth/midias'
      path: '/midias'
      fullPath: '/midias'
      preLoaderRoute: typeof AuthMidiasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notificacoes': {
      id: '/_auth/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthNotificacoesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/oferta': {
      id: '/_auth/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof AuthOfertaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/perfil': {
      id: '/_auth/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthPerfilRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/relatorios': {
      id: '/_auth/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthRelatoriosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/usuarios': {
      id: '/_auth/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthUsuariosRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAgendaRoute: typeof AuthAgendaRoute
  AuthAniversariantesRoute: typeof AuthAniversariantesRoute
  AuthArquivosRoute: typeof AuthArquivosRoute
  AuthConfiguracoesRoute: typeof AuthConfiguracoesRoute
  AuthFotosRoute: typeof AuthFotosRoute
  AuthGraficosRoute: typeof AuthGraficosRoute
  AuthGruposRoute: typeof AuthGruposRoute
  AuthLicoesRoute: typeof AuthLicoesRoute
  AuthMembrosRoute: typeof AuthMembrosRoute
  AuthMidiasRoute: typeof AuthMidiasRoute
  AuthNotificacoesRoute: typeof AuthNotificacoesRoute
  AuthOfertaRoute: typeof AuthOfertaRoute
  AuthPerfilRoute: typeof AuthPerfilRoute
  AuthRelatoriosRoute: typeof AuthRelatoriosRoute
  AuthUsuariosRoute: typeof AuthUsuariosRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAgendaRoute: AuthAgendaRoute,
  AuthAniversariantesRoute: AuthAniversariantesRoute,
  AuthArquivosRoute: AuthArquivosRoute,
  AuthConfiguracoesRoute: AuthConfiguracoesRoute,
  AuthFotosRoute: AuthFotosRoute,
  AuthGraficosRoute: AuthGraficosRoute,
  AuthGruposRoute: AuthGruposRoute,
  AuthLicoesRoute: AuthLicoesRoute,
  AuthMembrosRoute: AuthMembrosRoute,
  AuthMidiasRoute: AuthMidiasRoute,
  AuthNotificacoesRoute: AuthNotificacoesRoute,
  AuthOfertaRoute: AuthOfertaRoute,
  AuthPerfilRoute: AuthPerfilRoute,
  AuthRelatoriosRoute: AuthRelatoriosRoute,
  AuthUsuariosRoute: AuthUsuariosRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  BemVindoRoute: BemVindoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
